import { nanoid } from 'nanoid';
import { db } from '../../database.js';
import { FairRandom,blackjackScore,createFairSecret,isBlackjack,shuffledDeck,type Card,type FairSecret } from '../../game-engine.js';
import { changeBalance,checkedWager,emitWallet,gameWallet,loadSession,recordRound,saveSession } from '../shared/wallet.js';

export type BlackjackState={id:string;status:'playing'|'won'|'lost'|'push';outcome?:string;wager:number;payout:number;deck:Card[];player:Card[];dealer:Card[];proof:FairSecret;createdAt:number};
function blackjackView(state:BlackjackState|undefined){if(!state)return undefined;const finished=state.status!=='playing';return{id:state.id,status:state.status,outcome:state.outcome,wager:state.wager,payout:state.payout,player:state.player,dealer:finished?state.dealer:[state.dealer[0],{hidden:true}],playerScore:blackjackScore(state.player),dealerScore:finished?blackjackScore(state.dealer):undefined,canDouble:!finished&&state.player.length===2,proof:{serverSeedHash:state.proof.serverSeedHash,clientSeed:state.proof.clientSeed,nonce:state.proof.nonce,...(finished?{serverSeed:state.proof.serverSeed}:{})}};}
function settleBlackjack(userId:string,state:BlackjackState,outcome:string,payout:number,status:BlackjackState['status']){state.status=status;state.outcome=outcome;state.payout=payout;if(payout>0)changeBalance(userId,payout,'payout','blackjack',state.id);saveSession(userId,'blackjack',state);recordRound(userId,'blackjack',state.id,state.wager,payout,outcome,state.proof,{player:state.player,dealer:state.dealer},state.createdAt);return blackjackView(state);}
function dealerPlay(state:BlackjackState){while(blackjackScore(state.dealer)<17)state.dealer.push(state.deck.pop()!);}
function compareBlackjack(userId:string,state:BlackjackState){dealerPlay(state);const player=blackjackScore(state.player),dealer=blackjackScore(state.dealer);if(dealer>21||player>dealer)return settleBlackjack(userId,state,'玩家获胜',state.wager*2,'won');if(player===dealer)return settleBlackjack(userId,state,'平局',state.wager,'push');return settleBlackjack(userId,state,'庄家获胜',0,'lost');}
export function blackjackState(userId:string){return blackjackView(loadSession<BlackjackState>(userId,'blackjack'));}
export function startBlackjack(userId:string,wagerValue:number){const wager=checkedWager(wagerValue);const existing=loadSession<BlackjackState>(userId,'blackjack');if(existing?.status==='playing')throw new Error('当前 21 点对局尚未结束');const result=db.transaction(()=>{const id=nanoid();changeBalance(userId,-wager,'wager','blackjack',id);const proof=createFairSecret(`${userId}:${id}`);const deck=shuffledDeck(new FairRandom(proof));const state:BlackjackState={id,status:'playing',wager,payout:0,deck,player:[deck.pop()!,deck.pop()!],dealer:[deck.pop()!,deck.pop()!],proof,createdAt:Date.now()};if(isBlackjack(state.player)){const dealerBlackjack=isBlackjack(state.dealer);return dealerBlackjack?settleBlackjack(userId,state,'双方 Blackjack',wager,'push'):settleBlackjack(userId,state,'Blackjack',Math.floor(wager*2.5),'won');}saveSession(userId,'blackjack',state);return blackjackView(state);})();emitWallet(userId);return{state:result,wallet:gameWallet(userId)};}
export function blackjackAction(userId:string,action:'hit'|'stand'|'double'){const result=db.transaction(()=>{const state=loadSession<BlackjackState>(userId,'blackjack');if(!state||state.status!=='playing')throw new Error('没有进行中的 21 点对局');if(action==='double'){if(state.player.length!==2)throw new Error('只能在前两张牌时加倍');changeBalance(userId,-state.wager,'wager','blackjack',state.id);state.wager*=2;state.player.push(state.deck.pop()!);if(blackjackScore(state.player)>21)return settleBlackjack(userId,state,'玩家爆牌',0,'lost');return compareBlackjack(userId,state);}if(action==='hit'){state.player.push(state.deck.pop()!);const score=blackjackScore(state.player);if(score>21)return settleBlackjack(userId,state,'玩家爆牌',0,'lost');if(score===21)return compareBlackjack(userId,state);saveSession(userId,'blackjack',state);return blackjackView(state);}return compareBlackjack(userId,state);})();emitWallet(userId);return{state:result,wallet:gameWallet(userId)};}
