import { z } from 'zod';
import { defineGame, encodeGameInvitation } from '../../game-plugins/sdk.js';
import { actTexas, closeTexasRoom, createTexasRoom, joinTexasRoom, leaveTexasRoom, startTexasHand, texasActiveRoomId, texasRooms, texasState, watchTexasRoom } from './index.js';

const inviteCooldown=new Map<string,number>();
const RESEND_MS=5_000;
export function clearTexasInviteCooldown(roomId:string){for(const key of inviteCooldown.keys())if(key.endsWith(`:${roomId}`))inviteCooldown.delete(key);}

export const texasHoldemPlugin=defineGame({manifest:{id:'texas-holdem',name:'德州扑克',version:1,mode:'room',description:'2–6 人实时牌桌，支持观战、边池与可验证洗牌',supportsInvites:true},register(host){
  host.on('game:texas-holdem:rooms',(raw,{user,requireSpace})=>{const{spaceId}=z.object({spaceId:z.string()}).parse(raw);requireSpace(spaceId);return texasRooms(spaceId,user.id);});
  host.on('game:texas-holdem:create',(raw,{socket,user,requireSpace})=>{const value=z.object({spaceId:z.string(),smallBlind:z.number().int(),buyIn:z.number().int(),maxPlayers:z.number().int().min(2).max(6)}).parse(raw);requireSpace(value.spaceId);const state=createTexasRoom(value.spaceId,user.id,value.smallBlind,value.buyIn,value.maxPlayers);socket.join(`texas:${state.roomId}`);return state;});
  host.on('game:texas-holdem:join',(raw,{socket,user,requireSpace})=>{const value=z.object({spaceId:z.string(),roomId:z.string()}).parse(raw);requireSpace(value.spaceId);const state=joinTexasRoom(value.roomId,value.spaceId,user.id);socket.join(`texas:${state.roomId}`);return state;});
  host.on('game:texas-holdem:watch',(raw,{socket,user,requireSpace})=>{const value=z.object({spaceId:z.string(),roomId:z.string()}).parse(raw);requireSpace(value.spaceId);const state=watchTexasRoom(value.roomId,value.spaceId,user.id);socket.join(`texas:${state.roomId}`);return state;});
  host.on('game:texas-holdem:start',(raw,{user,requireSpace})=>{const{roomId}=z.object({roomId:z.string()}).parse(raw);const preview=texasState(roomId,user.id);requireSpace(preview.spaceId);return startTexasHand(roomId,user.id);});
  host.on('game:texas-holdem:act',(raw,{user,requireSpace})=>{const value=z.object({roomId:z.string(),action:z.enum(['fold','check','call','raise','all-in']),raiseTo:z.number().int().positive().optional()}).parse(raw);const preview=texasState(value.roomId,user.id);requireSpace(preview.spaceId);return actTexas(value.roomId,user.id,value.action,value.raiseTo);});
  host.on('game:texas-holdem:leave',(raw,{socket,user})=>{const{roomId}=z.object({roomId:z.string()}).parse(raw);leaveTexasRoom(roomId,user.id);socket.leave(`texas:${roomId}`);return true;});
  host.on('game:texas-holdem:close',(raw,{socket,user,requireSpace})=>{const{roomId}=z.object({roomId:z.string()}).parse(raw);const preview=texasState(roomId,user.id);requireSpace(preview.spaceId);closeTexasRoom(roomId,user.id);socket.leave(`texas:${roomId}`);return true;});
  host.on('game:texas-holdem:invite',(raw,{user,requireSpace,socketsForUser,createDirectMessage})=>{const value=z.object({spaceId:z.string(),roomId:z.string(),targetUserId:z.string()}).parse(raw);const members=requireSpace(value.spaceId);const target=members.find(member=>member.id===value.targetUserId);if(!target)throw new Error('该用户不在当前社区');if(target.id===user.id)throw new Error('不能邀请自己');const state=texasState(value.roomId,user.id);if(state.spaceId!==value.spaceId)throw new Error('牌桌不属于当前社区');if(!['waiting','finished'].includes(state.status)||state.players.length>=state.maxPlayers)throw new Error('牌局已经开始、牌桌已关闭或牌桌已满');if(!state.players.some(player=>player.id===user.id))throw new Error('只有牌桌玩家可以邀请成员');if(texasActiveRoomId(target.id))throw new Error('对方正在其他德州扑克牌桌中');const targetSockets=socketsForUser(target.id);if(!targetSockets.length)throw new Error('该成员当前不在线');const key=`${user.id}:${target.id}:${state.roomId}`,now=Date.now();if((inviteCooldown.get(key)??0)>now)throw new Error('邀请已发送，请稍后再试');const canResendAt=now+RESEND_MS;inviteCooldown.set(key,canResendAt);const expiresAt=now+60_000;const envelope={gameId:'texas-holdem',spaceId:value.spaceId,roomId:value.roomId,title:'德州扑克牌桌邀请',wager:state.buyIn,pot:state.buyIn*2,expiresAt,metadata:{smallBlind:state.smallBlind,maxPlayers:state.maxPlayers}};const message=createDirectMessage(user,target.id,encodeGameInvitation(envelope));for(const recipientId of[user.id,target.id])for(const connected of socketsForUser(recipientId))connected.emit('dm:message',message);for(const connected of targetSockets)connected.emit('game:texas-holdem:invited',{...envelope,inviter:user,buyIn:state.buyIn,smallBlind:state.smallBlind});return{canResendAt,message};});
}});
