import { nanoid } from 'nanoid';
import { db } from '../../database.js';
import { createFairSecret } from '../../game-engine.js';
import { gameEvents } from '../shared/events.js';
import { changeBalance,checkedWager,emitWallet,recordRound } from '../shared/wallet.js';
import { poolGroup,rackPoolBalls,simulatePoolShot,validCuePosition,type PoolBall,type PoolGroup,type PoolFrame } from './physics.js';

db.exec(`CREATE TABLE IF NOT EXISTS game_pool_rooms(id TEXT PRIMARY KEY,space_id TEXT NOT NULL,host_user_id TEXT NOT NULL,guest_user_id TEXT,wager INTEGER NOT NULL,status TEXT NOT NULL,state_json TEXT NOT NULL,winner_user_id TEXT,result TEXT,round_number INTEGER NOT NULL DEFAULT 1,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);CREATE INDEX IF NOT EXISTS idx_game_pool_space_time ON game_pool_rooms(space_id,updated_at DESC);`);
type Status='waiting'|'playing'|'finished';
type Player={id:string;seat:0|1;group?:PoolGroup};
type Shot={id:string;shooterId:string;frames:PoolFrame[];pocketed:number[];foul:boolean;message:string};
type Inner={balls:PoolBall[];players:Player[];currentUserId?:string;ballInHand:boolean;openTable:boolean;breakShot:boolean;shotNumber:number;lastShot?:Shot;rematchVotes:string[]};
type Row={id:string;spaceId:string;hostUserId:string;guestUserId?:string;wager:number;status:Status;stateJson:string;winnerUserId?:string;result?:string;roundNumber:number;createdAt:number;updatedAt:number};
const select=`SELECT id,space_id AS spaceId,host_user_id AS hostUserId,guest_user_id AS guestUserId,wager,status,state_json AS stateJson,winner_user_id AS winnerUserId,result,round_number AS roundNumber,created_at AS createdAt,updated_at AS updatedAt FROM game_pool_rooms`;
function row(roomId:string){return db.prepare(`${select} WHERE id=?`).get(roomId) as Row|undefined;}
function inner(value:Row){try{return JSON.parse(value.stateJson) as Inner;}catch{throw new Error('台球房间数据损坏');}}
function user(userId:string){const value=db.prepare('SELECT id,username,avatar_url AS avatarUrl FROM users WHERE id=?').get(userId) as {id:string;username:string;avatarUrl?:string}|undefined;if(!value)throw new Error('玩家不存在');return value;}
function emit(value:Row,closed=false){gameEvents.emit('pool:update',{spaceId:value.spaceId,roomId:value.id,closed});}
function update(roomId:string,state:Inner,extra:{status?:Status;winnerId?:string|null;result?:string|null}={}){db.prepare(`UPDATE game_pool_rooms SET state_json=?,status=COALESCE(?,status),winner_user_id=?,result=?,updated_at=? WHERE id=?`).run(JSON.stringify(state),extra.status??null,extra.winnerId??null,extra.result??null,Date.now(),roomId);return row(roomId)!;}
function active(userId:string){return db.prepare(`${select} WHERE status IN ('waiting','playing') AND (host_user_id=? OR guest_user_id=?) LIMIT 1`).get(userId,userId) as Row|undefined;}
export function poolActiveRoomId(userId:string){return active(userId)?.id;}
function remaining(state:Inner,group:PoolGroup){return state.balls.filter(ball=>!ball.pocketed&&poolGroup(ball.number)===group).length;}
export function poolState(roomId:string,userId:string){const value=row(roomId);if(!value)throw new Error('台球房间不存在');const state=inner(value);const me=state.players.find(player=>player.id===userId);return{roomId:value.id,spaceId:value.spaceId,wager:value.wager,pot:value.guestUserId?value.wager*2:value.wager,status:value.status,players:state.players.map(player=>({...user(player.id),seat:player.seat,group:player.group})),balls:state.balls,currentUserId:state.currentUserId,ballInHand:state.ballInHand,openTable:state.openTable,breakShot:state.breakShot,shotNumber:state.shotNumber,lastShot:state.lastShot,winnerId:value.winnerUserId,result:value.result,roundNumber:value.roundNumber,rematchVotes:state.rematchVotes,meSeat:me?.seat,canShoot:value.status==='playing'&&state.currentUserId===userId&&!state.ballInHand,canPlace:value.status==='playing'&&state.currentUserId===userId&&state.ballInHand,createdAt:value.createdAt,updatedAt:value.updatedAt};}
export function poolRooms(spaceId:string,userId:string){const values=db.prepare(`${select} WHERE space_id=? ORDER BY CASE status WHEN 'playing' THEN 0 WHEN 'waiting' THEN 1 ELSE 2 END,updated_at DESC LIMIT 30`).all(spaceId) as Row[];return values.map(value=>{const state=poolState(value.id,userId);return{roomId:state.roomId,status:state.status,wager:state.wager,pot:state.pot,players:state.players,roundNumber:state.roundNumber,winnerId:state.winnerId,updatedAt:state.updatedAt,isMine:state.meSeat!==undefined};});}
export function createPoolRoom(spaceId:string,userId:string,wagerValue:number){if(active(userId))throw new Error('你已经在一个台球房间中');const wager=checkedWager(wagerValue,{multiple:10}),id=nanoid(10),now=Date.now();const value=db.transaction(()=>{changeBalance(userId,-wager,'wager','pool',id);const state:Inner={balls:rackPoolBalls(),players:[{id:userId,seat:0}],ballInHand:false,openTable:true,breakShot:true,shotNumber:0,rematchVotes:[]};db.prepare(`INSERT INTO game_pool_rooms(id,space_id,host_user_id,wager,status,state_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)`).run(id,spaceId,userId,wager,'waiting',JSON.stringify(state),now,now);return row(id)!;})();emitWallet(userId);emit(value);return poolState(id,userId);}
export function joinPoolRoom(roomId:string,spaceId:string,userId:string){const value=db.transaction(()=>{const current=row(roomId);if(!current||current.spaceId!==spaceId)throw new Error('台球房间不存在');if(current.hostUserId===userId||current.guestUserId===userId)return current;if(active(userId))throw new Error('请先退出当前台球房间');if(current.status!=='waiting'||current.guestUserId)throw new Error('这个房间已经满了');changeBalance(userId,-current.wager,'wager','pool',roomId);const state=inner(current);state.players.push({id:userId,seat:1});state.currentUserId=current.hostUserId;db.prepare(`UPDATE game_pool_rooms SET guest_user_id=?,status='playing',state_json=?,updated_at=? WHERE id=?`).run(userId,JSON.stringify(state),Date.now(),roomId);return row(roomId)!;})();emitWallet(userId);emit(value);return poolState(roomId,userId);}
export function watchPoolRoom(roomId:string,spaceId:string,userId:string){const value=row(roomId);if(!value||value.spaceId!==spaceId)throw new Error('台球房间不存在');return poolState(roomId,userId);}
function settle(value:Row,state:Inner,winnerId:string,result:string){changeBalance(winnerId,value.wager*2,'payout','pool',value.id);const proof=createFairSecret(`pool:${value.id}:${value.roundNumber}`);for(const player of state.players)recordRound(player.id,'pool',`${value.id}:${value.roundNumber}:${player.id}`,value.wager,player.id===winnerId?value.wager*2:0,player.id===winnerId?'获胜':result,proof,{winnerId,result,roundNumber:value.roundNumber},value.createdAt);return update(value.id,state,{status:'finished',winnerId,result});}
export function placePoolCue(roomId:string,userId:string,x:number,y:number){const value=row(roomId);if(!value||value.status!=='playing')throw new Error('当前没有进行中的球局');const state=inner(value);if(state.currentUserId!==userId||!state.ballInHand)throw new Error('现在不能放置母球');if(!Number.isFinite(x)||!Number.isFinite(y)||!validCuePosition(state.balls,x,y))throw new Error('母球不能放在这里');const cue=state.balls.find(ball=>ball.number===0)!;cue.x=x;cue.y=y;cue.pocketed=false;state.ballInHand=false;const next=update(roomId,state);emit(next);return poolState(roomId,userId);}
export function shootPool(roomId:string,userId:string,angle:number,power:number){const value=row(roomId);if(!value||value.status!=='playing')throw new Error('当前没有进行中的球局');const state=inner(value),shooter=state.players.find(player=>player.id===userId);if(!shooter)throw new Error('你不是本桌玩家');if(state.currentUserId!==userId)throw new Error('还没轮到你');if(state.ballInHand)throw new Error('请先放置母球');if(!Number.isFinite(angle)||!Number.isFinite(power)||power<.08||power>1)throw new Error('击球参数无效');const result=simulatePoolShot(state.balls,angle,power);state.balls=result.balls;const opponent=state.players.find(player=>player.id!==userId)!;let foul=!result.firstContact||result.cuePocketed;const firstGroup=result.firstContact===8?'eight':poolGroup(result.firstContact??0);if(!state.openTable&&shooter.group&&firstGroup!==shooter.group&&(firstGroup==='eight'||firstGroup))foul=true;
  const objectPocketed=result.pocketed.filter(number=>number!==0&&number!==8);if(state.openTable&&!state.breakShot&&!foul){const assigned=objectPocketed.map(poolGroup).find(Boolean);if(assigned){shooter.group=assigned;opponent.group=assigned==='solids'?'stripes':'solids';state.openTable=false;}}
  let winnerId:string|undefined,finishResult:string|undefined;
  if(result.pocketed.includes(8)){const legal=!state.openTable&&!!shooter.group&&remaining(state,shooter.group)===0&&!foul;winnerId=legal?userId:opponent.id;finishResult=legal?'合法打进 8 号球':'提前或犯规打进 8 号球';}
  const ownPocketed=objectPocketed.some(number=>state.openTable||poolGroup(number)===shooter.group);state.breakShot=false;state.shotNumber++;
  if(!winnerId&&(foul||!ownPocketed)){state.currentUserId=opponent.id;state.ballInHand=foul;}
  if(result.cuePocketed){const cue=state.balls.find(ball=>ball.number===0)!;cue.pocketed=true;}
  state.lastShot={id:nanoid(8),shooterId:userId,frames:result.frames,pocketed:result.pocketed,foul,message:winnerId?finishResult!:foul?'犯规，对手获得自由球':ownPocketed?'继续击球':'交换球权'};state.rematchVotes=[];
  const next=db.transaction(()=>winnerId?settle(value,state,winnerId,finishResult!):update(roomId,state))();if(winnerId){for(const player of state.players)emitWallet(player.id);}emit(next);return poolState(roomId,userId);}
export function resignPool(roomId:string,userId:string){const next=db.transaction(()=>{const value=row(roomId);if(!value||value.status!=='playing')throw new Error('当前没有进行中的球局');const state=inner(value);if(!state.players.some(player=>player.id===userId))throw new Error('你不是本桌玩家');const winner=state.players.find(player=>player.id!==userId)!;return settle(value,state,winner.id,'对手认输');})();for(const player of inner(next).players)emitWallet(player.id);emit(next);return poolState(roomId,userId);}
export function rematchPool(roomId:string,userId:string){const next=db.transaction(()=>{const value=row(roomId);if(!value||value.status!=='finished'||!value.guestUserId)throw new Error('当前不能再来一局');const old=inner(value);if(!old.players.some(player=>player.id===userId))throw new Error('只有本桌玩家可以发起再来一局');old.rematchVotes=[...new Set([...old.rematchVotes,userId])];if(old.rematchVotes.length<2)return update(roomId,old,{status:'finished',winnerId:value.winnerUserId??null,result:value.result??null});changeBalance(value.hostUserId,-value.wager,'wager','pool',roomId);changeBalance(value.guestUserId!,-value.wager,'wager','pool',roomId);const players:Player[]=old.players.map(player=>({id:player.id,seat:player.seat}));const state:Inner={balls:rackPoolBalls(),players,currentUserId:players[value.roundNumber%2].id,ballInHand:false,openTable:true,breakShot:true,shotNumber:0,rematchVotes:[]};db.prepare(`UPDATE game_pool_rooms SET status='playing',state_json=?,winner_user_id=NULL,result=NULL,round_number=round_number+1,updated_at=? WHERE id=?`).run(JSON.stringify(state),Date.now(),roomId);return row(roomId)!;})();if(next.status==='playing'){emitWallet(next.hostUserId);emitWallet(next.guestUserId!);}emit(next);return poolState(roomId,userId);}
export function leavePoolRoom(roomId:string,userId:string){const value=row(roomId);if(!value)return true;if(value.status==='waiting'&&value.hostUserId===userId){db.transaction(()=>{changeBalance(userId,value.wager,'payout','pool',roomId);db.prepare('DELETE FROM game_pool_rooms WHERE id=?').run(roomId);})();emitWallet(userId);emit(value,true);return true;}if(value.status==='playing'&&(value.hostUserId===userId||value.guestUserId===userId)){resignPool(roomId,userId);return true;}return true;}
