import { z } from 'zod';
import { defineGame,encodeGameInvitation } from '../../game-plugins/sdk.js';
import { createPoolRoom,joinPoolRoom,leavePoolRoom,placePoolCue,poolActiveRoomId,poolRooms,poolState,rematchPool,resignPool,shootPool,watchPoolRoom } from './index.js';
const cooldown=new Map<string,number>(),RESEND_MS=5_000;
export function clearPoolInviteCooldown(roomId:string){for(const key of cooldown.keys())if(key.endsWith(`:${roomId}`))cooldown.delete(key);}
export const poolPlugin=defineGame({manifest:{id:'pool',name:'8 球台球',version:1,mode:'room',description:'双人实时 8 球、观战与积分对局',supportsInvites:true},register(host){
  host.on('game:pool:rooms',(raw,{user,requireSpace})=>{const{spaceId}=z.object({spaceId:z.string()}).parse(raw);requireSpace(spaceId);return poolRooms(spaceId,user.id);});
  host.on('game:pool:create',(raw,{socket,user,requireSpace})=>{const value=z.object({spaceId:z.string(),wager:z.number().int()}).parse(raw);requireSpace(value.spaceId);const state=createPoolRoom(value.spaceId,user.id,value.wager);socket.join(`pool:${state.roomId}`);return state;});
  host.on('game:pool:join',(raw,{socket,user,requireSpace})=>{const value=z.object({spaceId:z.string(),roomId:z.string()}).parse(raw);requireSpace(value.spaceId);const state=joinPoolRoom(value.roomId,value.spaceId,user.id);socket.join(`pool:${state.roomId}`);return state;});
  host.on('game:pool:watch',(raw,{socket,user,requireSpace})=>{const value=z.object({spaceId:z.string(),roomId:z.string()}).parse(raw);requireSpace(value.spaceId);const state=watchPoolRoom(value.roomId,value.spaceId,user.id);socket.join(`pool:${state.roomId}`);return state;});
  host.on('game:pool:shoot',(raw,{user,requireSpace})=>{const value=z.object({roomId:z.string(),angle:z.number(),power:z.number()}).parse(raw);const state=shootPool(value.roomId,user.id,value.angle,value.power);requireSpace(state.spaceId);return state;});
  host.on('game:pool:place',(raw,{user,requireSpace})=>{const value=z.object({roomId:z.string(),x:z.number(),y:z.number()}).parse(raw);const state=placePoolCue(value.roomId,user.id,value.x,value.y);requireSpace(state.spaceId);return state;});
  host.on('game:pool:resign',(raw,{user,requireSpace})=>{const state=resignPool(z.object({roomId:z.string()}).parse(raw).roomId,user.id);requireSpace(state.spaceId);return state;});
  host.on('game:pool:rematch',(raw,{user,requireSpace})=>{const state=rematchPool(z.object({roomId:z.string()}).parse(raw).roomId,user.id);requireSpace(state.spaceId);return state;});
  host.on('game:pool:leave',(raw,{socket,user})=>{const{roomId}=z.object({roomId:z.string()}).parse(raw);leavePoolRoom(roomId,user.id);socket.leave(`pool:${roomId}`);return true;});
  host.on('game:pool:invite',(raw,{user,requireSpace,socketsForUser,createDirectMessage})=>{const value=z.object({spaceId:z.string(),roomId:z.string(),targetUserId:z.string()}).parse(raw),members=requireSpace(value.spaceId),target=members.find(member=>member.id===value.targetUserId);if(!target)throw new Error('该用户不在当前社区');if(target.id===user.id)throw new Error('不能邀请自己');const state=poolState(value.roomId,user.id);if(state.spaceId!==value.spaceId||state.status!=='waiting'||state.players.length!==1||!state.players.some(player=>player.id===user.id))throw new Error('只有等待中的房主可以邀请成员');if(poolActiveRoomId(target.id))throw new Error('对方正在其他台球对局中');const sockets=socketsForUser(target.id);if(!sockets.length)throw new Error('该成员当前不在线');const key=`${user.id}:${target.id}:${state.roomId}`,now=Date.now();if((cooldown.get(key)??0)>now)throw new Error('邀请已发送，请稍后再试');const canResendAt=now+RESEND_MS;cooldown.set(key,canResendAt);const invitation={spaceId:value.spaceId,roomId:state.roomId,wager:state.wager,pot:state.wager*2,inviter:user,expiresAt:now+60_000};const message=createDirectMessage(user,target.id,encodeGameInvitation({gameId:'pool',spaceId:invitation.spaceId,roomId:invitation.roomId,title:'8 球台球邀请',wager:invitation.wager,pot:invitation.pot,expiresAt:invitation.expiresAt}));for(const id of[user.id,target.id])for(const connected of socketsForUser(id))connected.emit('dm:message',message);for(const connected of sockets)connected.emit('game:pool:invited',invitation);return{canResendAt,invitation,message};});
}});
