import { useEffect, useState } from 'react';
import { Check, Club, Coins, Eye, LogOut, Play, ShieldCheck, Sparkles, Spade, UserPlus, Users, X } from 'lucide-react';
import cover from '../../assets/games/texas-holdem-cover.svg';
import { BetControls, FairBadge, formatPoints, GameStage } from '../shared/components';
import type { GameInviteMember } from '../shared/types';
import type { TexasCard, TexasRoom, TexasState } from './types';

const streetName:Record<TexasState['street'],string>={waiting:'等待开局',preflop:'翻牌前',flop:'翻牌圈',turn:'转牌圈',river:'河牌圈',showdown:'摊牌',finished:'本手结束'};
const actionName:Record<string,string>={fold:'弃牌',check:'过牌',call:'跟注',raise:'加注','all-in':'全下','timeout-fold':'超时弃牌','timeout-check':'超时过牌'};

export function TexasHoldemGame({state,rooms,smallBlind,setSmallBlind,buyIn,setBuyIn,maxPlayers,setMaxPlayers,busy,onCreate,onOpen,onStart,onAction,onLeave,onCloseRoom,onInvite}:{state?:TexasState;rooms:TexasRoom[];smallBlind:number;setSmallBlind:(value:number)=>void;buyIn:number;setBuyIn:(value:number)=>void;maxPlayers:number;setMaxPlayers:(value:number)=>void;busy:boolean;onCreate:()=>void;onOpen:(room:TexasRoom)=>void;onStart:()=>void;onAction:(action:'fold'|'check'|'call'|'raise'|'all-in',raiseTo?:number)=>void;onLeave:()=>void;onCloseRoom:()=>void;onInvite:()=>void}){
  const [raiseTo,setRaiseTo]=useState(0);const [,setClock]=useState(Date.now());
  useEffect(()=>{if(state){const seat=state.me==='spectator'?undefined:state.me.seat;const player=state.players.find(item=>item.seat===seat);setRaiseTo(Math.min(player?player.streetBet+player.stack:state.minRaiseTo,Math.max(state.minRaiseTo,state.currentBet+state.bigBlind)))}},[state?.roomId,state?.handId,state?.currentBet,state?.minRaiseTo]);
  useEffect(()=>{if(!state?.actionDeadline)return;const timer=window.setInterval(()=>setClock(Date.now()),250);return()=>window.clearInterval(timer)},[state?.actionDeadline]);
  if(!state)return <GameStage title="德州扑克" eyebrow="TEXAS HOLD’EM" description="2–6 人服务端权威牌桌；完整下注轮、边池、观战和可验证洗牌。" icon={<Club/>} accent="#f0b85a" art={cover}>
    <div className="texas-room-browser"><header><span><Spade/><b>社区牌桌</b><small>{rooms.length} 张牌桌</small></span><i>LIVE TABLES</i></header><div className="texas-room-list">{rooms.length?rooms.map(room=><button key={room.roomId} disabled={busy} onClick={()=>onOpen(room)}><span className="texas-room-icon"><Club/></span><span><b>{room.players.map(player=>player.username).join(' · ')||'空牌桌'}</b><small>盲注 {formatPoints(room.smallBlind)}/{formatPoints(room.bigBlind)} · 带入 {formatPoints(room.buyIn)} · {room.players.length}/{room.maxPlayers} 人</small></span>{room.isMine&&<em>我的牌桌</em>}<strong>{room.status==='playing'&&!room.isMine?'观战':room.isMine?'返回':'加入'} <Play/></strong></button>):<div className="texas-empty"><Spade/><b>还没有德州扑克牌桌</b><span>创建第一桌，邀请社区在线成员加入。</span></div>}</div></div>
    <div className="game-control-panel texas-create-panel"><div className="texas-rule-card"><ShieldCheck/><span><b>积分筹码托管</b><small>带入后转为牌桌筹码，离桌时按剩余筹码退回。</small></span></div><BetControls value={smallBlind} setValue={value=>{setSmallBlind(value);if(buyIn<value*20)setBuyIn(value*20)}} disabled={busy}/><label className="texas-field"><span>带入筹码</span><input type="number" min={smallBlind*20} step={smallBlind} value={buyIn} onChange={event=>setBuyIn(Math.max(smallBlind*20,Number(event.target.value)||smallBlind*20))}/></label><label className="texas-field"><span>牌桌人数</span><div>{[2,4,6].map(value=><button className={maxPlayers===value?'active':''} key={value} onClick={()=>setMaxPlayers(value)}>{value} 人</button>)}</div></label><div className="texas-feature-list"><span><Check/>30 秒操作倒计时</span><span><Check/>全下与多层边池</span><span><Check/>观战不泄露底牌</span><span><Check/>每手公开洗牌证明</span></div><button className="primary-game-action" disabled={busy||buyIn<smallBlind*20} onClick={onCreate}><Club/>带入 {formatPoints(buyIn)} 创建牌桌</button></div>
  </GameStage>;

  const mySeat=state.me==='spectator'?undefined:state.me.seat;const me=state.players.find(player=>player.seat===mySeat);const maximum=me?me.streetBet+me.stack:0;const deadline=Math.max(0,Math.ceil(((state.actionDeadline??0)-Date.now())/1000));const current=state.players.find(player=>player.id===state.currentUserId);const winnerText=state.winners.map(winner=>`${state.players.find(player=>player.id===winner.userId)?.username??'玩家'} ${winner.handName} +${formatPoints(winner.amount)}`).join(' · ');
  return <GameStage title="德州扑克" eyebrow={`TABLE ${state.roomId.toUpperCase()} · HAND ${state.handNumber}`} description={`${streetName[state.street]} · 盲注 ${formatPoints(state.smallBlind)}/${formatPoints(state.bigBlind)}`} icon={<Club/>} accent="#f0b85a" art={cover}>
    <div className="texas-table-shell"><div className="texas-felt"><div className="texas-community"><small>{streetName[state.street]}</small><div>{Array.from({length:5},(_,index)=><TexasCardView key={index} card={state.community[index]}/>)}</div><b><Coins/>底池 {formatPoints(state.pot)}</b></div>{state.players.map(player=><TexasSeat key={player.id} player={player} active={state.currentUserId===player.id} me={player.id===me?.id} deadline={state.currentUserId===player.id?deadline:0}/>)}{state.status==='finished'&&<div className="texas-result"><Sparkles/><b>{winnerText||'本手牌结束'}</b><span>房主可以开始下一手，玩家也可以带着剩余筹码离桌。</span></div>}</div></div>
    <div className="game-control-panel texas-controls"><FairBadge proof={state.proof}/><div className="texas-status"><span><small>CURRENT ACTION</small><b>{state.status==='playing'?(state.canAct?'轮到你':`${current?.username??'玩家'} 思考中`):streetName[state.street]}</b></span>{state.status==='playing'&&<strong>{deadline}s</strong>}</div>{state.lastAction&&<div className="texas-last-action">{state.players.find(player=>player.id===state.lastAction!.userId)?.username} {actionName[state.lastAction.action]??state.lastAction.action}{state.lastAction.amount?` ${formatPoints(state.lastAction.amount)}`:''}</div>}<div className="texas-table-info"><span>你的筹码 <b>{me?formatPoints(me.stack):'观战'}</b></span><span>当前下注 <b>{formatPoints(state.currentBet)}</b></span><span>需要跟注 <b>{formatPoints(state.toCall)}</b></span></div>
      {state.status==='playing'&&state.canAct&&me&&<><div className="texas-quick-actions"><button disabled={busy} onClick={()=>onAction('fold')}>弃牌</button>{state.toCall===0?<button disabled={busy} onClick={()=>onAction('check')}>过牌</button>:<button className="call" disabled={busy} onClick={()=>onAction('call')}>跟注 {formatPoints(Math.min(state.toCall,me.stack))}</button>}<button className="allin" disabled={busy} onClick={()=>onAction('all-in')}>全下</button></div>{maximum>state.currentBet&&<div className="texas-raise"><label><span>加注到</span><b>{formatPoints(raiseTo)}</b></label><input type="range" min={Math.min(maximum,state.minRaiseTo)} max={maximum} step={Math.max(1,state.smallBlind)} value={Math.min(maximum,raiseTo)} onChange={event=>setRaiseTo(Number(event.target.value))}/><button disabled={busy||raiseTo<=state.currentBet} onClick={()=>onAction('raise',raiseTo)}>确认加注</button></div>}</>}
      {state.status!=='playing'&&state.canStart&&<button className="primary-game-action" disabled={busy} onClick={onStart}><Play/>开始第 {state.handNumber+1} 手</button>}{state.status!=='playing'&&me&&<button className="texas-invite" disabled={busy||state.players.length>=state.maxPlayers} onClick={onInvite}><UserPlus/>邀请在线成员</button>}<div className="texas-bottom-actions">{me&&<button disabled={busy||state.status==='playing'} onClick={onLeave}><LogOut/>离桌并结算</button>}{state.hostUserId===me?.id&&<button className="danger" disabled={busy||state.status==='playing'} onClick={onCloseRoom}><X/>解散牌桌</button>}{!me&&<span><Eye/>观战模式</span>}</div></div>
  </GameStage>;
}

function TexasCardView({card,small=false}:{card?:TexasCard;small?:boolean}){if(!card)return <i className={`texas-card empty ${small?'small':''}`}/>;const symbol=card.suit==='spades'?'♠':card.suit==='hearts'?'♥':card.suit==='diamonds'?'♦':'♣';const red=card.suit==='hearts'||card.suit==='diamonds';return <i className={`texas-card ${red?'red':''} ${small?'small':''}`}><b>{card.rank}</b><span>{symbol}</span></i>}
function TexasSeat({player,active,me,deadline}:{player:TexasState['players'][number];active:boolean;me:boolean;deadline:number}){return <article className={`texas-seat seat-${player.seat} ${active?'active':''} ${player.status==='folded'?'folded':''} ${me?'me':''}`}><div>{player.avatarUrl?<img src={player.avatarUrl} alt=""/>:<span>{player.username.slice(0,1).toUpperCase()}</span>}{player.isDealer&&<i>D</i>}</div><section><b>{player.username}{me?'（你）':''}</b><small>{formatPoints(player.stack)} 筹码{player.blind==='small'?' · SB':player.blind==='big'?' · BB':''}</small></section><aside>{player.hole.length?player.hole.map((card,index)=><TexasCardView card={card} small key={index}/>):Array.from({length:player.cardsHidden},(_,index)=><i className="texas-card back small" key={index}/>)}</aside>{player.streetBet>0&&<em>{formatPoints(player.streetBet)}</em>}{player.status==='all-in'&&<strong>ALL IN</strong>}{active&&<progress max={30} value={deadline}/>}</article>}

export function TexasInvitePicker({members,invited,now,busy,buyIn,onInvite,onClose}:{members:GameInviteMember[];invited:Record<string,number>;now:number;busy:string;buyIn:number;onInvite:(member:GameInviteMember)=>void;onClose:()=>void}){return <div className="gomoku-invite-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section className="gomoku-invite-picker"><header><div><Users/><span><b>邀请加入德州扑克牌桌</b><small>对方加入时将带入 {formatPoints(buyIn)} 积分</small></span></div><button onClick={onClose}><X/></button></header><div className="gomoku-invite-members">{members.length?members.map(member=>{const resendAt=invited[member.id]??0,cooling=resendAt>now;return <article key={member.id}><div className="gomoku-invite-avatar">{member.avatarUrl?<img src={member.avatarUrl} alt=""/>:member.username.slice(0,1).toUpperCase()}</div><span><b>{member.username}</b><small><i/>在线</small></span><button disabled={!!busy||cooling} onClick={()=>onInvite(member)}>{busy===member.id?'发送中…':cooling?`已邀请 ${Math.ceil((resendAt-now)/1000)}s`:resendAt?'重新邀请':'邀请'}</button></article>}):<div className="gomoku-invite-empty"><UserPlus/><b>暂无可邀请成员</b></div>}</div></section></div>}
