import { nanoid } from 'nanoid';
import { db } from '../../database.js';
import { crashMultiplier,crashPoint,createFairSecret,type FairSecret } from '../../game-engine.js';
import { changeBalance,checkedWager,emitWallet,gameWallet,recordRound } from '../shared/wallet.js';
import { gameEvents } from '../shared/events.js';

db.exec(`CREATE TABLE IF NOT EXISTS game_crash_bets (round_id TEXT NOT NULL,space_id TEXT NOT NULL,user_id TEXT NOT NULL,wager INTEGER NOT NULL,status TEXT NOT NULL,cashout_multiplier REAL,payout INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL,PRIMARY KEY(round_id,user_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);`);
type CrashPhase='betting'|'running'|'crashed';
type CrashRoom={spaceId:string;roundId:string;phase:CrashPhase;proof:FairSecret;crashAt:number;bettingEndsAt:number;startedAt?:number;endedAt?:number;timer?:NodeJS.Timeout;ticker?:NodeJS.Timeout};
const crashRooms=new Map<string,CrashRoom>();
function emitCrash(spaceId:string){gameEvents.emit('crash:update',{spaceId});}
function createCrashRound(spaceId:string){const roundId=nanoid();const proof=createFairSecret(`poio:${spaceId}:${roundId}`);const room:CrashRoom={spaceId,roundId,phase:'betting',proof,crashAt:crashPoint(proof),bettingEndsAt:Date.now()+5_000};crashRooms.set(spaceId,room);emitCrash(spaceId);room.timer=setTimeout(()=>startCrashRound(room),5_000);room.timer.unref();return room;}
function startCrashRound(room:CrashRoom){if(crashRooms.get(room.spaceId)!==room)return;room.phase='running';room.startedAt=Date.now();emitCrash(room.spaceId);room.ticker=setInterval(()=>{if(crashRooms.get(room.spaceId)!==room||room.phase!=='running')return;if(crashMultiplier(Date.now()-(room.startedAt??Date.now()))>=room.crashAt){finishCrashRound(room);return;}emitCrash(room.spaceId);},100);room.ticker.unref();}
function finishCrashRound(room:CrashRoom){if(room.phase!=='running')return;room.phase='crashed';room.endedAt=Date.now();if(room.ticker)clearInterval(room.ticker);db.prepare(`UPDATE game_crash_bets SET status='lost' WHERE round_id=? AND status='playing'`).run(room.roundId);const lost=db.prepare(`SELECT user_id AS userId,wager FROM game_crash_bets WHERE round_id=? AND status='lost'`).all(room.roundId) as Array<{userId:string;wager:number}>;for(const bet of lost)recordRound(bet.userId,'crash',`${room.roundId}:${bet.userId}`,bet.wager,0,`爆点 ${room.crashAt.toFixed(2)}x`,room.proof,{spaceId:room.spaceId,crashAt:room.crashAt},room.bettingEndsAt-5_000);emitCrash(room.spaceId);room.timer=setTimeout(()=>createCrashRound(room.spaceId),3_500);room.timer.unref();}
function crashRoom(spaceId:string){return crashRooms.get(spaceId)??createCrashRound(spaceId);}
function crashCurrentMultiplier(room:CrashRoom){if(room.phase==='betting')return 1;if(room.phase==='crashed')return room.crashAt;return crashMultiplier(Date.now()-(room.startedAt??Date.now()));}
export function crashState(spaceId:string,userId:string){const room=crashRoom(spaceId);const myBet=db.prepare(`SELECT wager,status,cashout_multiplier AS cashoutMultiplier,payout FROM game_crash_bets WHERE round_id=? AND user_id=?`).get(room.roundId,userId);const bets=db.prepare(`SELECT b.user_id AS userId,u.username,b.wager,b.status,b.cashout_multiplier AS cashoutMultiplier,b.payout FROM game_crash_bets b JOIN users u ON u.id=b.user_id WHERE b.round_id=? ORDER BY b.created_at ASC`).all(room.roundId);return{spaceId,roundId:room.roundId,phase:room.phase,multiplier:crashCurrentMultiplier(room),bettingEndsAt:room.bettingEndsAt,startedAt:room.startedAt,endedAt:room.endedAt,bets,myBet,proof:{serverSeedHash:room.proof.serverSeedHash,clientSeed:room.proof.clientSeed,nonce:room.proof.nonce,...(room.phase==='crashed'?{serverSeed:room.proof.serverSeed,crashAt:room.crashAt}:{})}};}
export function placeCrashBet(spaceId:string,userId:string,wagerValue:number){const wager=checkedWager(wagerValue);const room=crashRoom(spaceId);if(room.phase!=='betting'||Date.now()>=room.bettingEndsAt)throw new Error('本轮下注已经结束');db.transaction(()=>{const exists=db.prepare('SELECT 1 FROM game_crash_bets WHERE round_id=? AND user_id=?').get(room.roundId,userId);if(exists)throw new Error('本轮已经下注');changeBalance(userId,-wager,'wager','crash',room.roundId);db.prepare(`INSERT INTO game_crash_bets(round_id,space_id,user_id,wager,status,created_at) VALUES(?,?,?,?,?,?)`).run(room.roundId,spaceId,userId,wager,'playing',Date.now());})();emitWallet(userId);emitCrash(spaceId);return{state:crashState(spaceId,userId),wallet:gameWallet(userId)};}
export function cashoutCrash(spaceId:string,userId:string){const room=crashRoom(spaceId);if(room.phase!=='running')throw new Error('当前不在可结算阶段');const multiplier=crashCurrentMultiplier(room);if(multiplier>=room.crashAt)throw new Error('本轮已经爆点');const result=db.transaction(()=>{const bet=db.prepare(`SELECT wager,status FROM game_crash_bets WHERE round_id=? AND user_id=?`).get(room.roundId,userId) as {wager:number;status:string}|undefined;if(!bet)throw new Error('本轮还没有下注');if(bet.status!=='playing')throw new Error('本轮已经结算');const payout=Math.floor(bet.wager*multiplier);changeBalance(userId,payout,'payout','crash',room.roundId);db.prepare(`UPDATE game_crash_bets SET status='cashed',cashout_multiplier=?,payout=? WHERE round_id=? AND user_id=?`).run(multiplier,payout,room.roundId,userId);recordRound(userId,'crash',`${room.roundId}:${userId}`,bet.wager,payout,`${multiplier.toFixed(2)}x 结算`,room.proof,{spaceId,crashAt:room.crashAt,cashoutMultiplier:multiplier},room.bettingEndsAt-5_000);return payout;})();emitWallet(userId);emitCrash(spaceId);return{payout:result,state:crashState(spaceId,userId),wallet:gameWallet(userId)};}
