import { useEffect,useMemo,useRef,useState,type PointerEvent } from 'react';
import { Check,CircleDotDashed,Coins,Eye,LogOut,Play,Sparkles,Swords,UserPlus,X } from 'lucide-react';
import poolCover from '../../assets/games/pool-cover.svg';
import { BetControls,formatPoints,GameStage } from '../shared/components';
import type { GameInviteMember } from '../shared/types';
import type { PoolBall,PoolRoom,PoolState } from './types';

const BALL_COLORS=['#f5f2e8','#f3c534','#2368c4','#ef414f','#7453bd','#ef7c29','#26975a','#7a251f','#161922','#f3c534','#2368c4','#ef414f','#7453bd','#ef7c29','#26975a','#7a251f'];
function Ball({ball}:{ball:PoolBall}){if(ball.pocketed)return null;const stripe=ball.number>=9;return <g transform={`translate(${ball.x} ${ball.y})`}><circle r="13" fill={stripe?'#f7f4eb':BALL_COLORS[ball.number]} stroke="rgba(0,0,0,.32)" strokeWidth="2"/>{stripe&&<path d="M-12-5 A13 13 0 0 1 12-5 L12 5 A13 13 0 0 1-12 5Z" fill={BALL_COLORS[ball.number]}/>} {ball.number>0&&<><circle r="6.2" fill="#f6f4ec"/><text y="3.5" textAnchor="middle" fontSize="9" fontWeight="900" fill="#10131b">{ball.number}</text></>}</g>}

export function PoolGame({state,rooms,wager,setWager,busy,onCreate,onOpen,onShoot,onPlace,onResign,onRematch,onLeave,onInvite}:{state?:PoolState;rooms:PoolRoom[];wager:number;setWager:(value:number)=>void;busy:boolean;onCreate:()=>void;onOpen:(room:PoolRoom)=>void;onShoot:(angle:number,power:number)=>void;onPlace:(x:number,y:number)=>void;onResign:()=>void;onRematch:()=>void;onLeave:()=>void;onInvite:()=>void}){
  const[power,setPower]=useState(.55),[aim,setAim]=useState(0),[displayBalls,setDisplayBalls]=useState<PoolBall[]>(state?.balls??[]);const animation=useRef(0);
  useEffect(()=>{window.clearInterval(animation.current);const frames=state?.lastShot?.frames??[];if(frames.length){let index=0;setDisplayBalls(frames[0].balls);animation.current=window.setInterval(()=>{index++;if(index>=frames.length){window.clearInterval(animation.current);setDisplayBalls(state!.balls);return}setDisplayBalls(frames[index].balls)},24)}else setDisplayBalls(state?.balls??[]);return()=>window.clearInterval(animation.current)},[state?.lastShot?.id,state?.roomId]);
  useEffect(()=>{if(state&&!state.lastShot)setDisplayBalls(state.balls)},[state?.updatedAt]);
  if(!state)return <GameStage title="8 球台球" eyebrow="POIO 8-BALL" description="创建球桌或加入社区成员的房间；轨迹、碰撞、犯规和积分结算全部由服务端判定。" icon={<CircleDotDashed/>} accent="#35d6a3" art={poolCover}>
    <div className="gomoku-room-browser"><div className="gomoku-browser-head"><span><CircleDotDashed/><b>社区球桌</b><small>{rooms.filter(room=>room.status!=='finished').length} 桌可加入</small></span><i>LIVE</i></div><div className="gomoku-room-list">{rooms.length===0?<div className="gomoku-empty"><CircleDotDashed/><b>还没有人摆下球桌</b><span>创建第一桌，在线成员会立即看到。</span></div>:rooms.map(room=><button key={room.roomId} onClick={()=>onOpen(room)} disabled={busy}><div className="pool-room-balls"><i>8</i><i/></div><span><b>{room.players.map(player=>player.username).join(' vs ')||'等待玩家'}</b><small>每人 {formatPoints(room.wager)} 积分 · 第 {room.roundNumber} 局 · {room.status==='waiting'?'等待对手':room.status==='playing'?'进行中':'已结束'}</small></span>{room.isMine&&<em>我的球桌</em>}<strong>{room.isMine?'返回':room.status==='waiting'?'加入':'观战'}<Play size={12}/></strong></button>)}</div></div>
    <div className="game-control-panel gomoku-lobby-controls"><div className="gomoku-rule-mark"><CircleDotDashed/><span><b>标准双人 8 球</b><small>分组后清空自己的目标球，再合法打进 8 号球获胜。</small></span></div><BetControls value={wager} setValue={setWager} disabled={busy}/><div className="gomoku-pot-preview"><Coins/><span><small>双方奖池</small><b>{formatPoints(wager*2)} 积分</b></span></div><div className="gomoku-feature-list"><span><Check/>服务端统一物理模拟</span><span><Check/>犯规后对手获得自由球</span><span><Check/>支持实时观战和再来一局</span></div><button className="primary-game-action" disabled={busy} onClick={onCreate}><CircleDotDashed/>押 {formatPoints(wager)} 积分创建</button></div>
  </GameStage>;
  const me=state.players.find(player=>player.seat===state.meSeat),turn=state.players.find(player=>player.id===state.currentUserId),winner=state.players.find(player=>player.id===state.winnerId);const cue=displayBalls.find(ball=>ball.number===0&&!ball.pocketed);const myVote=!!me&&state.rematchVotes.includes(me.id);const headline=state.status==='waiting'?'等待另一位玩家加入':state.status==='finished'?`${winner?.username??'玩家'} 获胜`:state.canPlace?'请在球桌上放置母球':state.canShoot?'轮到你击球':state.meSeat===undefined?`正在观战 · ${turn?.username??'玩家'} 击球`:`等待 ${turn?.username??'对手'} 击球`;
  const pointer=(event:PointerEvent<SVGSVGElement>)=>{const rect=event.currentTarget.getBoundingClientRect(),x=(event.clientX-rect.left)/rect.width*1000,y=(event.clientY-rect.top)/rect.height*500;if(state.canPlace){onPlace(x,y);return}if(state.canShoot&&cue)setAim(Math.atan2(y-cue.y,x-cue.x));};
  const aimEnd=cue?{x:cue.x+Math.cos(aim)*145,y:cue.y+Math.sin(aim)*145}:undefined;
  return <GameStage title="8 球台球" eyebrow={`ROUND ${state.roundNumber}`} description={headline} icon={<CircleDotDashed/>} accent="#35d6a3" art={poolCover}>
    <div className="pool-table-shell"><svg className={`pool-table ${state.canPlace?'placing':''}`} viewBox="0 0 1000 500" onPointerDown={pointer} onPointerMove={event=>{if(event.buttons)pointer(event)}}><rect x="12" y="12" width="976" height="476" rx="64" fill="#633c22"/><rect x="38" y="38" width="924" height="424" rx="42" fill="#086551"/><rect x="54" y="54" width="892" height="392" rx="18" fill="#08745b" stroke="#169578" strokeWidth="3"/>{[[54,54],[500,48],[946,54],[54,446],[500,452],[946,446]].map(([x,y],index)=><circle key={index} cx={x} cy={y} r="25" fill="#090d13"/>)}{state.canShoot&&cue&&aimEnd&&<><line x1={cue.x} y1={cue.y} x2={aimEnd.x} y2={aimEnd.y} stroke="#fff" strokeOpacity=".65" strokeWidth="2" strokeDasharray="8 8"/><line x1={cue.x-Math.cos(aim)*32} y1={cue.y-Math.sin(aim)*32} x2={cue.x-Math.cos(aim)*250} y2={cue.y-Math.sin(aim)*250} stroke="#d7b887" strokeWidth="8" strokeLinecap="round"/></>}{displayBalls.map(ball=><Ball key={ball.number} ball={ball}/>)}</svg>{state.status==='finished'&&<div className="pool-result"><Sparkles/><b>{headline}</b><span>{state.result} · 赢得 {formatPoints(state.pot)} 积分</span></div>}</div>
    <div className="game-control-panel pool-controls"><div className="gomoku-turn playing"><i/><span><small>MATCH STATUS</small><b>{headline}</b></span></div><div className="pool-players">{state.players.map(player=><div key={player.id} className={player.id===state.currentUserId?'active':''}><span className="pool-player-avatar">{player.avatarUrl?<img src={player.avatarUrl}/>:player.username.slice(0,1).toUpperCase()}</span><span><b>{player.username}{player.id===me?.id?'（你）':''}</b><small>{player.group==='solids'?'全色球 1–7':player.group==='stripes'?'花色球 9–15':'尚未分组'}</small></span></div>)}</div><div className="gomoku-match-info"><span>房间码 <b>{state.roomId.toUpperCase()}</b></span><span>奖池 <b>{formatPoints(state.pot)}</b></span><span>杆数 <b>{state.shotNumber}</b></span></div>{state.lastShot&&<div className={`pool-shot-message ${state.lastShot.foul?'foul':''}`}>{state.lastShot.message}</div>}{state.canShoot&&<><label className="pool-power"><span>击球力度 <b>{Math.round(power*100)}%</b></span><input type="range" min="8" max="100" value={Math.round(power*100)} onChange={event=>setPower(Number(event.target.value)/100)}/></label><button className="primary-game-action" disabled={busy} onClick={()=>onShoot(aim,power)}><Swords/>击球</button></>}{state.status==='waiting'&&me&&<button className="primary-game-action" disabled={busy} onClick={onInvite}><UserPlus/>邀请在线成员</button>}{state.status==='finished'&&me&&<button className="primary-game-action" disabled={busy||myVote} onClick={onRematch}><Swords/>{myVote?'等待对手同意':'再来一局'}</button>}{state.status==='playing'&&me&&<button className="gomoku-danger" disabled={busy} onClick={onResign}>认输</button>}<button className="gomoku-leave" disabled={busy} onClick={onLeave}><LogOut/>{state.status==='waiting'&&me?'解散球桌':'离开球桌'}</button>{state.meSeat===undefined&&<div className="gomoku-spectating"><Eye/>观战模式</div>}</div>
  </GameStage>;
}

export function PoolInvitePicker({members,invited,now,busy,wager,onInvite,onClose}:{members:GameInviteMember[];invited:Record<string,number>;now:number;busy:string;wager:number;onInvite:(member:GameInviteMember)=>void;onClose:()=>void}){return <div className="gomoku-invite-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section className="gomoku-invite-picker"><header><div><UserPlus/><span><b>邀请在线成员打台球</b><small>对方加入时将支付 {formatPoints(wager)} 积分</small></span></div><button onClick={onClose}><X/></button></header><div className="gomoku-invite-members">{members.length===0?<div className="gomoku-invite-empty"><UserPlus/><b>暂无可邀请的在线成员</b></div>:members.map(member=>{const resendAt=invited[member.id]??0,cooling=resendAt>now;return <article key={member.id}><div className="gomoku-invite-avatar">{member.avatarUrl?<img src={member.avatarUrl}/>:member.username.slice(0,1).toUpperCase()}</div><span><b>{member.username}</b><small><i/>在线</small></span><button disabled={!!busy||cooling} onClick={()=>onInvite(member)}>{busy===member.id?'发送中…':cooling?<><Check/>已邀请 {Math.ceil((resendAt-now)/1000)}s</>:<><UserPlus/>邀请</>}</button></article>})}</div></section></div>}
