import { nanoid } from 'nanoid';
import { db } from '../../database.js';
import { FairRandom,createFairSecret,minesMultiplier,type FairSecret } from '../../game-engine.js';
import { changeBalance,checkedWager,emitWallet,gameWallet,loadSession,recordRound,saveSession } from '../shared/wallet.js';
export type MinesState={id:string;status:'playing'|'won'|'lost';wager:number;payout:number;mineCount:number;mines:number[];revealed:number[];proof:FairSecret;createdAt:number;outcome?:string};
function minesView(state:MinesState|undefined){if(!state)return undefined;const finished=state.status!=='playing';const multiplier=minesMultiplier(state.mineCount,state.revealed.length);return{id:state.id,status:state.status,outcome:state.outcome,wager:state.wager,payout:state.payout,mineCount:state.mineCount,revealed:state.revealed,multiplier,nextPayout:Math.floor(state.wager*multiplier),...(finished?{mines:state.mines}:{}),proof:{serverSeedHash:state.proof.serverSeedHash,clientSeed:state.proof.clientSeed,nonce:state.proof.nonce,...(finished?{serverSeed:state.proof.serverSeed}:{})}};}
export function minesState(userId:string){return minesView(loadSession<MinesState>(userId,'mines'));}
export function startMines(userId:string,wagerValue:number,mineCount:number){const wager=checkedWager(wagerValue);if(!Number.isSafeInteger(mineCount)||mineCount<1||mineCount>20)throw new Error('地雷数量必须为 1–20');const existing=loadSession<MinesState>(userId,'mines');if(existing?.status==='playing')throw new Error('当前 Mines 对局尚未结束');const result=db.transaction(()=>{const id=nanoid();changeBalance(userId,-wager,'wager','mines',id);const proof=createFairSecret(`${userId}:${id}`);const random=new FairRandom(proof);const cells=Array.from({length:25},(_,index)=>index);for(let index=cells.length-1;index>0;index--){const other=random.int(index+1);[cells[index],cells[other]]=[cells[other],cells[index]];}const state:MinesState={id,status:'playing',wager,payout:0,mineCount,mines:cells.slice(0,mineCount).sort((a,b)=>a-b),revealed:[],proof,createdAt:Date.now()};saveSession(userId,'mines',state);return minesView(state);})();emitWallet(userId);return{state:result,wallet:gameWallet(userId)};}
export function revealMineCell(userId:string,cell:number){if(!Number.isSafeInteger(cell)||cell<0||cell>=25)throw new Error('格子编号无效');const result=db.transaction(()=>{const state=loadSession<MinesState>(userId,'mines');if(!state||state.status!=='playing')throw new Error('没有进行中的 Mines 对局');if(state.revealed.includes(cell))return minesView(state);if(state.mines.includes(cell)){state.status='lost';state.outcome='踩中地雷';saveSession(userId,'mines',state);recordRound(userId,'mines',state.id,state.wager,0,state.outcome,state.proof,{mines:state.mines,revealed:state.revealed,hit:cell},state.createdAt);return minesView(state);}state.revealed.push(cell);state.revealed.sort((a,b)=>a-b);if(state.revealed.length===25-state.mineCount){const payout=Math.floor(state.wager*minesMultiplier(state.mineCount,state.revealed.length));state.status='won';state.payout=payout;state.outcome='清空安全格';changeBalance(userId,payout,'payout','mines',state.id);recordRound(userId,'mines',state.id,state.wager,payout,state.outcome,state.proof,{mines:state.mines,revealed:state.revealed},state.createdAt);}saveSession(userId,'mines',state);return minesView(state);})();emitWallet(userId);return{state:result,wallet:gameWallet(userId)};}
export function cashoutMines(userId:string){const result=db.transaction(()=>{const state=loadSession<MinesState>(userId,'mines');if(!state||state.status!=='playing')throw new Error('没有进行中的 Mines 对局');if(state.revealed.length===0)throw new Error('至少翻开一个安全格后才能结算');const payout=Math.floor(state.wager*minesMultiplier(state.mineCount,state.revealed.length));state.status='won';state.payout=payout;state.outcome='主动结算';changeBalance(userId,payout,'payout','mines',state.id);saveSession(userId,'mines',state);recordRound(userId,'mines',state.id,state.wager,payout,state.outcome,state.proof,{mines:state.mines,revealed:state.revealed},state.createdAt);return minesView(state);})();emitWallet(userId);return{state:result,wallet:gameWallet(userId)};}
